#comentario
version: 0.2

phases:
  install:
    commands:
      - mkdir /tmp/src/
      - mv $CODEBUILD_SRC_DIR/* /tmp/src/
      - cd /tmp/src/
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install --unsafe-perm 

  build:
    commands:
      - npm run build 
      - echo Build completed on $(date)

artifacts:
    files:
      - '**/*'
    base-directory: /tmp/src/build/
